<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SlotsGameEngine.BL\SlotsGameEngine.BL.csproj" />
		<ProjectReference Include="..\SlotsGameEngine.DTO\SlotsGameEngine.DTO.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>
</Project>
	